{"name": "verify logging into application", "status": "failed", "statusDetails": {"message": "AttributeError: module 'selenium.webdriver.chrome.webdriver' has no attribute 'Chrome'", "trace": "request = <FixtureRequest for <Function test_verify_logging_into_application>>, _pytest_bdd_example = {}\n\n    @pytest.mark.usefixtures(*args)\n    def scenario_wrapper(request, _pytest_bdd_example):\n        scenario = templated_scenario.render(_pytest_bdd_example)\n>       _execute_scenario(feature, scenario, request)\n\n..\\.virtualenvs\\AaaS_python_repo-qOQ6V3NE\\lib\\site-packages\\pytest_bdd\\scenario.py:174: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n..\\.virtualenvs\\AaaS_python_repo-qOQ6V3NE\\lib\\site-packages\\pytest_bdd\\scenario.py:144: in _execute_scenario\n    _execute_step_function(request, scenario, step, step_func)\n..\\.virtualenvs\\AaaS_python_repo-qOQ6V3NE\\lib\\site-packages\\pytest_bdd\\scenario.py:108: in _execute_step_function\n    kwargs = {arg: request.getfixturevalue(arg) for arg in get_args(step_func)}\n..\\.virtualenvs\\AaaS_python_repo-qOQ6V3NE\\lib\\site-packages\\pytest_bdd\\scenario.py:108: in <dictcomp>\n    kwargs = {arg: request.getfixturevalue(arg) for arg in get_args(step_func)}\n..\\.virtualenvs\\AaaS_python_repo-qOQ6V3NE\\lib\\site-packages\\_pytest\\fixtures.py:581: in getfixturevalue\n    fixturedef = self._get_active_fixturedef(argname)\n..\\.virtualenvs\\AaaS_python_repo-qOQ6V3NE\\lib\\site-packages\\_pytest\\fixtures.py:601: in _get_active_fixturedef\n    self._compute_fixture_value(fixturedef)\n..\\.virtualenvs\\AaaS_python_repo-qOQ6V3NE\\lib\\site-packages\\_pytest\\fixtures.py:687: in _compute_fixture_value\n    fixturedef.execute(request=subrequest)\n..\\.virtualenvs\\AaaS_python_repo-qOQ6V3NE\\lib\\site-packages\\_pytest\\fixtures.py:1072: in execute\n    result = hook.pytest_fixture_setup(fixturedef=self, request=request)\n..\\.virtualenvs\\AaaS_python_repo-qOQ6V3NE\\lib\\site-packages\\pluggy\\_hooks.py:265: in __call__\n    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)\n..\\.virtualenvs\\AaaS_python_repo-qOQ6V3NE\\lib\\site-packages\\pluggy\\_manager.py:80: in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n..\\.virtualenvs\\AaaS_python_repo-qOQ6V3NE\\lib\\site-packages\\_pytest\\fixtures.py:1126: in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n..\\.virtualenvs\\AaaS_python_repo-qOQ6V3NE\\lib\\site-packages\\_pytest\\fixtures.py:925: in call_fixture_func\n    fixture_result = next(generator)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\n    @pytest.fixture(scope='module')\n    def driver():\n>       driver = webdriver.Chrome(ChromeDriverManager().install())\nE       AttributeError: module 'selenium.webdriver.chrome.webdriver' has no attribute 'Chrome'\n\ntests\\myfixtures\\my_fixtures.py:10: AttributeError"}, "steps": [{"name": "Given user lands on login page", "status": "failed", "statusDetails": {"message": "module 'selenium.webdriver.chrome.webdriver' has no attribute 'Chrome'", "trace": "AttributeError: module 'selenium.webdriver.chrome.webdriver' has no attribute 'Chrome'\n"}, "start": 1636544299632, "stop": 1636544299639}], "start": 1636544299632, "stop": 1636544299639, "uuid": "0c5018d2-0ce0-e092-d6fc-ebb82520fb64", "historyId": "0c5018d20ce0e092d6fcebb82520fb64", "fullName": "features\\login.feature:verify logging into application", "labels": [{"name": "host", "value": "sasi-auto-py01"}, {"name": "thread", "value": "13760-MainThread"}, {"name": "framework", "value": "pytest-bdd"}, {"name": "language", "value": "cpython3"}, {"name": "feature", "value": "verify login functionality"}]}